language: php

php:
  - 7.4

before_install:
  - composer self-update

install:
  - composer install

script:
  - php vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
